# Generated by Django 2.2.10 on 2020-05-05 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='update',
            name='owner',
        ),
    ]
